<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Windowing.Glfw" Version="2.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Vertix.Engine\Vertix.Engine.csproj" />
    <ProjectReference Include="..\..\Vertix.Graphics.Text\Vertix.Graphics.Text.csproj" />
    <ProjectReference Include="..\..\Vertix.OpenGL\Vertix.OpenGL.csproj" />
    <ProjectReference Include="..\..\Vertix\Vertix.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Fonts\unifont-17.0.02.otf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Shaders\Passes\geometry_pass.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Shaders\Passes\geometry_pass.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Shaders\screen_sample.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Shaders\screen_sample.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Shaders\shader2D.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Shaders\shader2D.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Shaders\shader2D_font.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Shaders\shader3D.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Shaders\shader3D.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
