<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.Windowing.Sdl" Version="2.22.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Vertix.Direct3D11\Vertix.Direct3D11.csproj" />
    <ProjectReference Include="..\..\Vertix.Engine\Vertix.Engine.csproj" />
    <ProjectReference Include="..\..\Vertix\Vertix.csproj" />
  </ItemGroup>

</Project>
